[package]
name = "authc-cli"
version = "0.1.0"
authors = ["Songtronix <Songtronix@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2", features = ["yaml"] }
authc = { path = "../authc" }
tokio = { version = "=1.17.0", features = ["macros"] }