[package]
name = "assets_manager"
version = "0.7.2"
authors = ["Benoît du Garreau"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
description= "Conveniently load, cache, and reload external resources"

repository = "https://github.com/a1phyr/assets_manager"
documentation = "https://docs.rs/assets_manager"

categories = ["caching", "filesystem", "game-development"]
keywords = ["asset", "assets", "cache", "hot-reloading", "resources"]


[features]
default = ["ahash", "parking_lot"]
json = ["serde_json", "serde"]
ron = ["serde_ron", "serde"]
bincode = ["serde_bincode", "serde"]


hot-reloading = ["notify", "crossbeam-channel"]
embedded = ["assets_manager_macros"]

zip-bzip2 = ["zip", "zip/bzip2"]
zip-deflate = ["zip", "zip/deflate"]


cbor = ["serde_cbor", "serde"]

msgpack = ["serde_msgpack", "serde"]

yaml = ["serde_yaml", "serde"]
toml = ["serde_toml", "serde"]

flac = ["rodio/flac"]
mp3 = ["rodio/mp3"]
vorbis = ["rodio/vorbis"]
wav = ["rodio/wav"]

bmp = ["image/bmp"]
jpeg = ["image/jpeg"]
png = ["image/png"]
webp = ["image/webp"]

gltf = ["_gltf", "base64", "png", "jpeg"]

[dependencies]
log = {version = "0.4"}

assets_manager_macros = {path = "macros", version = "0.2", optional = true}

ahash = {version = "0.7.0", default-features = false, optional = true}
parking_lot = {version = "0.11", optional = true}

notify = {version = "4.0", optional = true}
crossbeam-channel = {version = "0.5", optional = true}

zip = {version = "0.5.13", default-features = false, optional = true}

serde = {version = "1.0", optional = true, features = ["derive"]}
serde_bincode = {version = "1.2", package = "bincode", optional = true}
serde_cbor = {version = "0.11", optional = true}
serde_json = {version = "1.0", optional = true}
serde_msgpack = {version = "0.15", package = "rmp-serde", optional = true}
serde_ron = {version = "0.7", package = "ron", optional = true}
serde_toml = {version = "0.5", package = "toml", optional = true}
serde_yaml = {version = "0.8.4", optional = true}

rodio = {version = "0.14", default-features = false, optional = true}
image = {version = "0.23.13", default-features = false, optional = true}
ab_glyph = {version = "0.2.12", optional = true}

_gltf = {version = "0.16", package = "gltf", default-features = false, optional = true}
base64 = {version = "0.13", optional = true}

[dev-dependencies]
cfg-if = "1.0"
rand = "0.8"
serde = {version = "1.0", features = ["derive"]}
env_logger = "0.9"