[package]
name = "iced_winit"
version = "0.3.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
description = "A winit runtime for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced_winit"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[features]
debug = ["iced_native/debug"]

[dependencies]
window_clipboard = "0.2"
log = "0.4"
thiserror = "1.0"

[dependencies.winit]
version = "0.26"
git = "https://github.com/iced-rs/winit"
rev = "02a12380960cec2f351c09a33d6a7cc2789d96a6"

[dependencies.iced_native]
version = "0.4"
path = "../native"

[dependencies.iced_graphics]
version = "0.2"
path = "../graphics"

[dependencies.iced_futures]
version = "0.3"
path = "../futures"

[dependencies.iced_lazy]
version = "0.1.0"
path = "../lazy"

[dependencies.iced_style]
version = "0.3"
path = "../style"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = ["Document", "Window"]
